# Generated by Django 3.2.4 on 2021-08-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id_film', models.IntegerField(primary_key=True, serialize=False)),
                ('judul_film', models.CharField(max_length=255)),
                ('sinopsis_film', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('bobottfidf', models.CharField(blank=True, editable=False, max_length=50)),
                ('labelfilm', models.CharField(blank=True, editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='historiuser',
            fields=[
                ('id_historiuser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('id_film', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='katanegatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='katapositif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userrekomen',
            fields=[
                ('id_rekom', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('rekomen', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='userreview',
            fields=[
                ('id_komentar', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('komentar', models.TextField()),
                ('labelkomen', models.CharField(blank=True, editable=False, max_length=10)),
                ('datafilm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='film.film')),
            ],
        ),
    ]
