# Generated by Django 3.2.4 on 2021-08-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbbosok',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kata', models.CharField(max_length=100)),
                ('frekuensi', models.IntegerField()),
                ('film', models.IntegerField()),
            ],
        ),
    ]
