# Generated by Django 3.2.4 on 2021-08-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_dbbosok'),
    ]

    operations = [
        migrations.CreateModel(
            name='historiuserpp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('film', models.IntegerField()),
                ('kata', models.CharField(max_length=100)),
                ('bobottfidf', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
