# Generated by Django 3.2.4 on 2021-07-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historiuser',
            fields=[
                ('id_historiuser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('id_film', models.TextField(default='')),
            ],
        ),
    ]
